<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '---- Select item ----' => '---- Item auswählen ----',
    'Action five ...' => 'Aktion fünf ...',
    'Action four ...' => 'Aktion vier ...',
    'Action one ...' => 'Aktion eins ...',
    'Action three ...' => 'Aktion drei ...',
    'Action two ...' => 'Aktion zwei ...',
    'Clear Table' => 'Tabelle leeren',
    'Code' => 'Code',
    'Column' => 'Spalte',
    'Create' => 'Erstellen',
    'DONE' => 'ERLEDIGT',
    'Details' => 'Details',
    'End Help' => 'Hilfe beenden',
    'Error Message' => 'Fehler Medlung',
    'Example' => 'Beispiel',
    'FAILED' => 'FEHLGESCHLAGEN',
    'Help' => 'Hilfe',
    'Info' => 'Info',
    'Modal Model' => 'Modal Model',
    'Modal with Tooltip' => 'Modal mit Kurzinfo',
    'Next »' => 'Weiter »',
    'No' => 'Nein',
    'Ok' => 'Ok',
    'Progress Bar' => 'Fortschrittsanzeige',
    'Requirement' => 'Voraussetzung',
    'Row' => 'Zeile',
    'SKIPPED' => 'ÜBERSPRUNGEN',
    'Show Modal' => 'Modal anzeigen',
    'Show Modal with Tooltip' => 'Zeige Modal mit Kurzinfo',
    'Show Progress' => 'Fortschritt anzeigen',
    'Showing modal for {model_name}' => 'Zeige modal für {model_name}',
    'Showing modal with tooltip' => 'Modal mit Kurzinfo zeigen',
    'Showing progress bar' => 'Fortschrittsanzeige anzeigen',
    'Start' => 'Start',
    'Submit' => 'Senden',
    'Update' => 'Aktualisieren',
    'Update Cell' => 'Aktualisere Zelle',
    'Updating Cell' => 'Zelle aktualiseren',
    'Value' => 'Wert',
    'Values {value} commited to server' => 'Werte {value} an Server gesendet',
    'Yes' => 'Ja',
    'first attribute' => 'erstes Attribut',
    'first item' => 'erstes Element',
    'row number' => 'Zeilennummer',
    'run third action?' => 'dritte Aktion durchführen?',
    'second attribute' => 'zweites Attribut',
    'second item' => 'zweites Element',
    'third attribute' => 'drittes Attribut',
    'third item' => 'drittes Element',
    '« Prev' => '« Zurück',
    'Please contact us if you think this is a server error. Thank you.' => 'Bitte kontaktieren Sie uns, wenn Sie glauben, dass dies ein Serverfehler ist. Vielen Dank.',
    'The above error occurred while the Web server was processing your request.' => 'Der obige Fehler ist aufgetreten, während der Webserver Ihre Anfrage verarbeitet hat.',
    'The file {path} couldn\'t be found.' => 'Die Datei {path} konnte nicht gefunden werden.',
    'Tourist-Page' => 'Tourist-Seite'
];
