<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error occurred while processing.' => 'Während der Verarbeitung ist ein Fehler aufgetreten.',
    'Can\'t set the label for the checkbox correctly.' => 'Das Label für das Kontrollkästchen kann nicht korrekt festgelegt werden.',
    'Clicking the <strong>question mark within the navbar</strong> will start the help tour for this page.' => 'Wenn Sie auf das <strong> Fragezeichen in der Navigationsleiste </strong> klicken, wird die Hilfetour für diese Seite gestartet.',
    'Clicking the button will open a modal window. The content for the modal window will be loaded using ajax. Within the modal the model will be validated.' => 'Durch das Drücken auf die Schaltfläche wird ein modales Fenster geöffnet. Der Inhalt für das modale Fenster wird mit Ajax geladen. Innerhalb des modalen Fensters wird das Model validiert.',
    'Clicking the button will open a modal window. Within the modal window a tooltip will be shown.' => 'Durch das Klicken auf die Schaltfläche wird ein modales Fenster geöffnet. Im modalen Fenster wird ein Tooltip angezeigt.',
    'Clicking the button will open a modal window. Within this modal you can start an process which shows visually the progress of the process.' => 'Durch Klicken auf die Schaltfläche wird ein modales Fenster geöffnet. Innerhalb dieses Modals können Sie einen Prozess starten, der den Fortschritt des Prozesses visuell anzeigt.',
    'Clicking the {-} will open an modal window. Within the modal you can create or update the value for this cell.' => 'Durch Klicken auf {-} wird ein modales Fenster geöffnet. Innerhalb des Modals können Sie den Wert für diese Zelle erstellen oder aktualisieren.',
    'For Attribute2 a value needs to be selected.' => 'Für Attribut2 muss ein Wert ausgewählt werden.',
    'Here you see an example, how the snippet is used within the application.' => 'Hier sehen Sie ein Beispiel, wie das Schnipsel in der Anwendung verwendet wird.',
    'Here you see the code used for this snippet.' => 'Hier sehen Sie den Code für diesen Schnipsel.',
    'Here you see the requirements for this snippet to work properly.' => 'Hier sehen Sie die Voraussetzungen, damit dieser Schnipsel ordnungsgemäß funktioniert.',
    'Label tooltip to give some usefull information for the input.' => 'Bezeichnung Kurzinfo um notwendige Information für die Eingabe zu geben.',
    'On this page are no helps available. See the {tour-page} for how to use this snippet.' => 'Auf dieser Seite ist keine Hilfe verfügbar. Auf der {tour-page} finden Sie Informationen zur Verwendung dieses Schnipsels.',
    'Running this process may take some time.' => 'Das Ausführen dieses Prozesses kann einige Zeit dauern.',
    'This example is based <strong>heavily</strong> on' => 'Dieses Beispiel basiert <strong>stark</strong> auf',
    'This snippet is not about handling long running scripts asynchronous. Its about to show the progress of scripts which are based on each other.' => 'Bei diesem Schnipsel geht es nicht darum, lange laufende Skripte asynchron zu behandeln. Es zeigt den Fortschritt von Skripten, die aufeinander aufbauen.',
    'This snippet uses only the session to store the table cell values.' => 'Dieses Schnipsel verwendet nur die Session zum Speichern der Tabellenzellenwerte.',
    'This shows what is needed to set up an yii2 project to be deployed to heroku.' => 'Dies zeigt, was zum Einrichten eines yii2-Projekts fürs hochladen zu Heroku erforderlich ist.',
];
